### ISSUE TITLE
Selenium crashes quite often if queries are executed back to back

### ISSUE THREAD

**Issue by ucyo** [usedgoodreads/usedgoodreads#10]
Experienced this quite often now. Especially if I interrupted the previous runtime of selenium I had to restart the whole container. Might be just an issue on my machine, might we should look into it, if it happens to more people.

**Comment by daniel-j-h** [comment]
Same here. Think we are not properly closing it which could be an issue.

Try the contextmanager:

    with Firefox() as driver:
        ..

Should in all cases clean up the driver :crossed_fingers:

**Comment by ucyo** [comment]
There is also a docker container for selenium including a pool of browsers ([docs](https://selenium-python.readthedocs.io/getting-started.html#using-selenium-with-remote-webdriver)). Adding this in the near future to the overall architecture might be useful

**Comment by daniel-j-h** [comment]
We did this.
