### ISSUE TITLE
Declare Code of Conduct: Define merge and pull request workflow

### ISSUE THREAD

**Issue by ucyo** [usedgoodreads/usedgoodreads#28]
Currently we have two branches: `develop` and `master`. The `develop` branch will be deployed `staging`. The `master` branch will be deployed as `production` (for details check #7). Following rules are suggested:

`master`
1. No pull requests will be accepted, except for ones manipulating only documentation or if the source is the `develop` branch.
2. All pull requests must based on the current HEAD of master -> A rebase is mandatory.
3. Travis CI/CD must run without problems (including unit and integration tests)

`develop`
1. Only one `feature branch` merge/pull request at a time. Before the current `feature branch` is declined or merged to `master` no pull requests are accepted
2. Rebase on master before opening a pull request (see 2 above)
3. Travis CI/CD must run without problems (including unit and integration tests)

`feature branch`
1. All other branches are treated as `feature branch`.
2. Lifetime should be shorter than 2 weeks. If feature is not merge till then either it is too big of a feature (solution: split to smaller chunks) or development postponed. 

Any ideas on each of the branches? Something I missed? Write up Code of Conduct?

**Comment by daniel-j-h** [comment]
re develop 1 - I think multiple prs against develop are fine, travis runs only if the branch is develop (!) so after merging into develop.

**Comment by daniel-j-h** [comment]
I think these guidelines would be great in a `CONTRIBUTING.md` file

https://github.blog/2012-09-17-contributing-guidelines/

so it shows up when people want to jump in.

**Comment by ucyo** [comment]
Fixed with 54498ac677ef488abc6e99e156745de075745477
