### ISSUE TITLE
Auto-update website if job status changes

### ISSUE THREAD

**Issue by ucyo** [usedgoodreads/usedgoodreads#30]
Currently the user has to manually update the website for getting information about the current status. Not user friendly :skunk:

**Comment by daniel-j-h** [comment]
Maybe we can just use meta refresh for now when we render the template for pending jobs

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta

e.g. pass `render_template(.., refresh=True)` and then in the template either set this meta refresh or not based on it.

**Comment by ucyo** [comment]
This refresh is executed once, right? It is not an endless loop....
How can we do this on something like a push notification? So that the server actually initiates the refresh? WebSockets? JS?

**Comment by daniel-j-h** [comment]
The meta refresh attribute tells the browser to refresh the page after n seconds. Then the new page has it again which results in the browser refreshing again after n seconds, and so on. Unless we no longer add it in our Jinja2 template e.g. because we have results.

**Comment by ucyo** [comment]
This should now be fixed in newest commit of #31
