### ISSUE TITLE
Set up Docker Hub to automatically build and publish images

### ISSUE THREAD

**Issue by daniel-j-h** [usedgoodreads/usedgoodreads#7]
We need some sort of CI/CD to build and publish images we can then download and run in production.

**Comment by daniel-j-h** [comment]
This is set up

https://hub.docker.com/r/usedgoodreads/usedgoodreads

auto-builds a backend and a frontend tag for every commit to master now.

Down the road we can have additional builds for specific tags, too.

**Comment by ucyo** [comment]
Nice :+1:
