### ISSUE TITLE
High-Level Architecture Design

### ISSUE THREAD

**Issue by daniel-j-h** [usedgoodreads/usedgoodreads#8]
@ucyo here's a write-up for what we talked about. Starting with an example flow

1. The user is looking at https://www.goodreads.com/book/show/36236132-growing-a-revolution

2. The user changes to https://www.usedgoodreads.com/book/show/36236132-growing-a-revolution

3. Our Flask API checks the database for `36236132-growing-a-revolution`: if we have used books and the date we got the booked is below a threshold, we return that to the user. Otherwise

4. We return the user `{ "status": "pending" }`. The user sets a timer and starts at step 2 e.g. every 10 seconds, while showing a loading icon.

5. If we've not seen the book before, that is there is no mapping `36236132-growing-a-revolution` -> `ISBN` in the database, we enqueue a job to make a GET request against https://www.goodreads.com/book/show/36236132-growing-a-revolution and fetch and store the mapping in the database. After the job stores the mapping in the database, it enqueues a new job to look for used books.

6. If we have seen the book before, we can skip the ISBN resolving step and can directly enqueues a new job to look for used books.

7. The async job queries used book stores, and when done writes results into the database.

---

```
+-api-------------------------------------------------------------------+
|                                                                       |
| https://www.usedgoodreads.com/book/show/36236132-growing-a-revolution |
|                                                                       |
+----------------------------+------------------------------------------+
                             |
                             |
                             |
+-key------------------------v---+                                 +-postgres---------------------+
|                                +--------------------------------->                              |
|  36236132-growing-a-revolution |                                 | Up to date used book results |
|                                <---------------------------------+                              |
+------------------------+---+---+                                 +-------------------------^----+
+-isbn------------+      |   |                                     +-fetch-----+             |
|                 <------+   +------------------------------------->           |             |
|  9780393608328  |                                                | Goodreads |             |
|                 <------------------------------------------------+           |             |
+-------------+---+                                                +-----------+             |
+-rq-------+  |                                                                              |
|          |  |                                                                              |
|  Worker  <--+                                                                              |
|          |                                                                                 |
+-------+--+                                                                                 |
        |                                                                                    |
        |                                                                                    |
        +------------------------------------------------------------------------------------+
```

@ucyo thoughts? It should mostly be in line with what we talked about earlier. Except for the added ISBN cache. I'd rather have the url to isbn resolition cached than having to make a request to goodreads for every query.

**Comment by ucyo** [comment]
Sounds good to me. The numerical part of the key `36236132-growing-a-revolution` is apparently the good reads internal ID of the book, but we should anyway save the whole route and add it to the database.

**Comment by daniel-j-h** [comment]
Perfect, just added a commit to do this

https://github.com/usedgoodreads/usedgoodreads/blob/c55fc3e5c620a02ff36f14edc2299e191f34d301/backend/usedgoodreads/__main__.py#L106-L107

**Comment by daniel-j-h** [comment]
We implement this by now! I'll add the architecture to the readme.
