### ISSUE TITLE
ISBN vs ISBN10 vs EAN

### ISSUE THREAD

**Issue by ucyo** [usedgoodreads/usedgoodreads#9]
Since in #8 we are talking about the architectural design, we should look into our database models. I was reading about the different identifications and what goodreads defines as ISBN is actually the EAN. This is nit-picking, but the basic difference is that the ISBN is defined including the hyphen. ISBN10 can be calculated from EAN/ISBN13 and is basically not used anymore. I would suggest we use EAN and comply to the standard. The advantage is, that it is an integer and operations might be faster than using string manipulations.

**Comment by daniel-j-h** [comment]
Cool, let's do this! :rocket: 

Quick note re. integer: right now the data type is just a string in the database. You can make it an int but then it probably has to be a big int (or whatever the appropriately sized type is called) and not a standard `db.Integer`.

**Comment by ucyo** [comment]
I will look into the appropiate type. Technically, since all book EAN must be within the range `978 * 10**10 <= EAN 980 * 10**10 -1`. There is room for optimized compression... :broken_heart:

**Comment by ucyo** [comment]
Closing this since for now we will stick with just calling it ISBN
